-- ============================================================
-- SUDAH DIGABUNG -- file ini dipertahankan hanya untuk histori.
-- ============================================================
-- Perbaikan di file ini (mengganti policy prototipe "using (true)"
-- pada tabel transaksi_stok_lampiran dengan policy
-- "auth.role() = 'authenticated'") SUDAH DIGABUNGKAN langsung ke
-- supabase/migrasi_bukti_transaksi_stok.sql.
--
-- - Project BARU (clone dari awal): TIDAK PERLU menjalankan file
--   ini. Cukup jalankan migrasi_bukti_transaksi_stok.sql yang sudah
--   memuat perbaikan ini.
-- - Project LAMA yang sudah pernah menjalankan file ini sebelumnya:
--   tidak perlu tindakan apa pun -- policy di database sudah dalam
--   keadaan benar (idempotent, aman dijalankan ulang kalau ragu).
-- ============================================================
