-- ============================================================
-- SUDAH DIGABUNG -- file ini dipertahankan hanya untuk histori.
-- ============================================================
-- Perbaikan di file ini (menambahkan
-- perform set_config('stokku.izinkan_ubah_jumlah', 'true', true)
-- sebelum UPDATE stok.jumlah di konfirmasi_terima_transfer) SUDAH
-- DIGABUNGKAN langsung ke supabase/migrasi_bukti_penerimaan.sql.
--
-- - Project BARU (clone dari awal): TIDAK PERLU menjalankan file
--   ini. Cukup jalankan migrasi_bukti_penerimaan.sql yang sudah
--   memuat perbaikan ini.
-- - Project LAMA yang sudah pernah menjalankan file ini sebelumnya:
--   tidak perlu tindakan apa pun -- function di database sudah
--   dalam keadaan benar (idempotent, aman dijalankan ulang kalau
--   ragu).
-- ============================================================
